name: Destroy PR Preview Deploy
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: foodler-customer-web
  GCP_REGION: europe-north1

on:
  pull_request:
    types: [closed]

jobs:
 destroy:
    name: destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Destroy Cloud Run PR Preview
        run: |
          gcloud run services delete ${{ env.SERVICE }}-preview-pr-${{ github.event.pull_request.number }} \
            --platform managed \
            --region ${{ env.GCP_REGION }}
